default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chunin_development

test:
  <<: *default
  database: chuning_test

production:
  <<: *default
  database: chunin_production
  username: chunin
  password: <%= ENV['CHUNIN_DATABASE_PASSWORD'] %>

